apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  labels:
    app: {{ include "frontend.name" . }}
data:
  REACT_APP_BACKEND_URL: {{ .Values.config.REACT_APP_BACKEND_URL | quote }}