apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "timescaledb.fullname" . }}-init-script
  labels:
    app: {{ include "timescaledb.name" . }}
data:
  init-db.sql: |-
{{ .Values.initSQL | indent 4 }}