apiVersion: v1
kind: Service
metadata:
  name: {{ include "timescaledb.fullname" . }}
  labels:
    app: {{ include "timescaledb.name" . }}
spec:
  selector:
    app: {{ include "timescaledb.name" . }}
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
