apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    app: {{ include "backend.name" . }}
data:
{{- range $k, $v := .Values.config }}
  {{ $k }}: {{ quote $v }}
{{- end }}